# Generated by Django 5.1.3 on 2024-11-25 19:53

import django.db.models.deletion
import producto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, max_length=1000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('numTlf', models.CharField(blank=True, max_length=17, null=True, validators=[producto.models.validate_phone_number])),
                ('web', models.TextField(blank=True, null=True)),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Fabricantes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidadEnStock', models.PositiveIntegerField(default=0)),
                ('categoria', models.TextField(choices=[('sillas', 'Sillas'), ('iluminación', 'Iluminación'), ('escritorios', 'Escritorios'), ('miscelánea', 'Miscelánea')], default='miscelánea')),
                ('destacado', models.BooleanField(default=False)),
                ('agotado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fabricante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='producto.fabricante')),
            ],
            options={
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
    ]
