# Generated by Django 5.1.3 on 2024-11-26 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_fabricante_numtlf_alter_fabricante_pais_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foto',
            old_name='image',
            new_name='imagen',
        ),
    ]
